-- New scraped listings from Somali developers (July 2026 batch 2)
-- Sources: Wafi Investment, Afrimac International

-- ============================================
-- WAFI INVESTMENT (wafiinvestment.com)
-- ============================================

INSERT INTO public.listings (service_type, lister_type, title, description, location, address, property_type, bedrooms, bathrooms, square_feet, sale_price, features, amenities, images, contact_phone, contact_whatsapp, verification_status, is_available, is_scraped, scraped_source, scraped_url)
VALUES
('sale', 'broker', 'Lumen — 1 & 2BR Apartments, 6th Parklands', 'Where Light Meets The City & Forest. Contemporary apartments overlooking Karura Forest on Limuru Road, 6th Parklands. 1BR from $60K, 2BR from $95K.', 'Parklands', 'Limuru Road, 6th Parklands, Nairobi', 'apartment', 2, 2, 1184, 12350000, ARRAY['1-2 Bedroom Options', 'Forest Facing', 'City Facing', '70-120 sqm'], ARRAY['Rooftop pool', 'Rooftop restaurant', 'Yoga studio', 'Co-working space', 'Fully fitted gym', 'Kids play area', 'Solar panels', 'High-speed lifts', 'CCTV surveillance', 'Borehole', 'Full backup power', 'Intercom system', 'Concierge'], ARRAY['https://static.wixstatic.com/media/1d50a8_7759dd3b2ff44a5c89b16b8d7bdf3494~mv2.jpg'], '+254720000082', '+254720000082', 'verified', true, true, 'Wafi Investment', 'https://www.wafiinvestment.com/lumen'),

('sale', 'broker', 'Westridge — 2-5BR + DSQ Apartments, Westlands', 'Refined residential development along Waiyaki Way, Westlands. 2BR from $95K, 3BR $145K, 4BR $165K, 5BR Duplex from $190K.', 'Westlands', 'Waiyaki Way, Westlands, Nairobi', 'apartment', 3, 3, 2099, 18850000, ARRAY['2-5 Bedroom + DSQ', '130-325 sqm', 'Duplex Available'], ARRAY['Rooftop pool', 'Rooftop garden', 'Fully fitted gym', 'Kids play area', 'Commercial area', 'Residents lounge', 'Courtyard', 'High-speed lifts', 'Borehole', 'Manned entrances'], ARRAY[]::text[], '+254720000082', '+254720000082', 'verified', true, true, 'Wafi Investment', 'https://www.wafiinvestment.com/westridge'),

('sale', 'broker', 'Wafi Square — 2-5BR + DSQ Mixed-Use, 2nd Parklands', 'Contemporary mixed-use residential in 2nd Parklands Avenue. 2BR from $70K, 3BR $100K, 4BR $135K, 5BR Duplex $200K.', 'Parklands', '2nd Parklands Avenue, Nairobi', 'apartment', 3, 3, 1722, 13000000, ARRAY['2-5 Bedroom + DSQ', '130-317 sqm', 'Mixed-Use', 'Duplex Available'], ARRAY['Rooftop pool', 'Prayer area', 'Commercial space', 'Residents lounge', 'Video intercom', 'Fully fitted gym', 'CCTV surveillance', 'High-speed lifts', 'Kids play area', 'Borehole', 'Manned entrances'], ARRAY[]::text[], '+254720000082', '+254720000082', 'verified', true, true, 'Wafi Investment', 'https://www.wafiinvestment.com/wafi-square'),

('sale', 'broker', 'Wafi Residence — 2-5BR + DSQ, 1st Parklands', 'A Calm Address in the City. Gated community in Batu Batu estate, 1st Avenue Parklands. 2BR from $70K, 3BR $115K, 4BR $135K, 5BR $330K.', 'Parklands', 'Batu Batu Estate, 1st Avenue Parklands, Nairobi', 'apartment', 3, 3, 1938, 14950000, ARRAY['2-5 Bedroom + DSQ', '128-330 sqm', 'Gated Community'], ARRAY['Rooftop terrace', 'Club house', 'Fully fitted gym', 'Kids play area', 'Solar panels', 'High-speed lifts', 'CCTV surveillance', 'Borehole', 'Full backup power', 'Intercom system', 'Ample parking'], ARRAY[]::text[], '+254720000082', '+254720000082', 'verified', true, true, 'Wafi Investment', 'https://www.wafiinvestment.com/wafi-residence');


-- ============================================
-- AFRIMAC INTERNATIONAL (afrimacinternational.com)
-- ============================================

INSERT INTO public.listings (service_type, lister_type, title, description, location, address, property_type, bedrooms, bathrooms, square_feet, sale_price, features, amenities, images, contact_phone, contact_whatsapp, verification_status, is_available, is_scraped, scraped_source, scraped_url)
VALUES
('sale', 'broker', '3BR Apartment — Jalaram Road, Westlands', 'Premium 3-bedroom apartment with staff quarter on Jalaram Road, Westlands. 152 sqm with heated rooftop infinity pool and sky lounge.', 'Westlands', 'Jalaram Road, Westlands, Nairobi', 'apartment', 3, 4, 1636, 19500000, ARRAY['152 sqm', 'DSQ', 'Private Balcony'], ARRAY['Heated infinity pool', 'Sky lounge', 'Fully equipped gym', 'Spa & sauna', 'Yoga deck', 'Landscaped gardens', 'Kids play area', 'Co-working space', 'High-speed lifts', 'Backup generator', 'Borehole', 'CCTV', 'Ample parking'], ARRAY['https://afrimacinternational.com/wp-content/uploads/2026/07/amani-kitchen-669x564.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/07/amani-residence-787-758x564.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/07/amani-residence-living-and-dining-45-758x564.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/07/amani-776-758x564.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/07/amani-residence-living-65-758x564.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/07/amani-residence-balcony-view-758x564.jpeg'], '+254721939689', '+254721939689', 'verified', true, true, 'Afrimac', 'https://afrimacinternational.com/property/3-bedroom-apartment-for-sale-jalaram-road-westlands/'),

('sale', 'broker', '2BR Apartment — Pangani', 'Affordable 2-bedroom apartment in Pangani off Thika Road. 100 sqm with modern finishes and full amenities.', 'Pangani', 'Thika Road, Pangani, Nairobi', 'apartment', 2, 2, 1076, 9100000, ARRAY['100 sqm', 'Modern Fitted Kitchen'], ARRAY['Borehole', '24/7 security', 'High-speed lifts', 'Backup generator', 'Fully equipped gym', 'Kids playground', 'Solar panels', 'Intercom system', 'Ample parking'], ARRAY['https://afrimacinternational.com/wp-content/uploads/2026/06/apartment-for-sale-in-pangani-787-487x564.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/06/apartment-for-sale-in-pangani-78756-487x564.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/06/apartment-for-sale-in-pangani-785-483x564.jpeg'], '+254721939689', '+254721939689', 'verified', true, true, 'Afrimac', 'https://afrimacinternational.com/property/affordable-2-bedroom-apartment-for-sale-in-pangani/'),

('sale', 'broker', '4BR Penthouse — General Mathenge, Westlands', 'Luxury 4-bedroom penthouse on General Mathenge Road. 316 sqm (3,400 sqft) with covered infinity pool, riverside garden, and spa. KES 55M.', 'Westlands', 'General Mathenge Road, Westlands, Nairobi', 'apartment', 4, 5, 3400, 55000000, ARRAY['316 sqm', 'DSQ', 'Penthouse', '3 Parking Spaces'], ARRAY['Covered infinity pool', 'Fully equipped gym', 'Riverside garden', 'BBQ area', 'Sauna', 'Backup generator', 'Borehole', 'Video intercom', 'Basement parking'], ARRAY['https://afrimacinternational.com/wp-content/uploads/2026/06/WhatsApp-Image-2025-01-16-at-22.06.08-2-758x564.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/06/WhatsApp-Image-2025-01-16-at-22.06.08-3-758x564.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/06/WhatsApp-Image-2025-01-16-at-22.06.08-758x564.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/06/WhatsApp-Image-2025-01-16-at-22.06.09-1-758x564.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/06/WhatsApp-Image-2025-01-16-at-22.06.09-2-758x564.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/06/WhatsApp-Image-2025-01-16-at-22.06.10-2-758x564.jpeg'], '+254721939689', '+254721939689', 'verified', true, true, 'Afrimac', 'https://afrimacinternational.com/property/4-bedroom-penthouse-for-sale-general-mathenge-westlands/'),

('sale', 'broker', '5BR Duplex + DSQ — 3rd Parklands (320 sqm)', 'Exclusive 5-bedroom duplex with DSQ in 3rd Parklands. 320 sqm with swimming pool and rooftop facilities. From $220K.', 'Parklands', '3rd Parklands, Nairobi', 'apartment', 5, 5, 3445, 28600000, ARRAY['320 sqm', 'DSQ', 'Duplex', 'Under Construction'], ARRAY['Swimming pool', 'Fully equipped gym', 'Kids play area', 'Backup generator', 'Borehole', 'Solar water heating', '24hr security', 'Ample parking', 'Restaurant', 'Retail facilities'], ARRAY['https://afrimacinternational.com/wp-content/uploads/2026/06/New-Picture-25.png', 'https://afrimacinternational.com/wp-content/uploads/2026/06/bedroom-1st-parklands.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/06/New-Picture-3.png', 'https://afrimacinternational.com/wp-content/uploads/2026/06/New-Picture-1.png'], '+254721939689', '+254721939689', 'verified', true, true, 'Afrimac', 'https://afrimacinternational.com/property/exclusive-5-bedroom-duplex-dsq-for-sale-in-parklands-320-sqm/'),

('sale', 'broker', '3BR Apartment — Kilimani', 'Spacious 3-bedroom apartment in Kilimani. 140 sqm with heated pool, jogging track, and landscaped gardens. From $115K.', 'Kilimani', 'Kilimani, Nairobi', 'apartment', 3, 2, 1507, 14950000, ARRAY['140 sqm', 'Modern Finishes'], ARRAY['Heated pool', 'Gym', 'Jogging track', 'BBQ area', 'Kids play area', 'Landscaped gardens', 'Backup generator', 'Borehole'], ARRAY['https://afrimacinternational.com/wp-content/uploads/2026/06/kilimani-full-view.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/06/kilimani-living-room.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/06/kilimani-shower.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/06/kilimani-bedroom-1.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/06/bedroom-kilimani-apartment-1.jpeg'], '+254721939689', '+254721939689', 'verified', true, true, 'Afrimac', 'https://afrimacinternational.com/property/for-sale-three-bedroom-apartment-in-kilimani/'),

('sale', 'broker', '2BR + DSQ Apartment — Parklands', 'Modern 2-bedroom with DSQ in Parklands. 108 sqm with rooftop terrace, prayer room, and spa. $77K.', 'Parklands', 'Parklands, Nairobi', 'apartment', 2, 2, 1163, 10010000, ARRAY['108 sqm', 'DSQ', 'Master Ensuite with Balcony'], ARRAY['Rooftop terrace', 'Fully equipped gym', 'Spa & sauna', 'Kids play area', 'High-speed lifts', 'Backup generator', 'Borehole', 'CCTV', 'BBQ area', 'Prayer room', 'Ample parking'], ARRAY['https://afrimacinternational.com/wp-content/uploads/2026/06/bedrooom-1st-parklands.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/06/1st-Parklands-bed.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/06/living-1st-parklands.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/06/dining-1st-Parklands.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/06/kids-play-area-1st-parklands.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/06/gym-1st-parklands.jpeg', 'https://afrimacinternational.com/wp-content/uploads/2026/06/rooftop-1st-parklands.jpeg'], '+254721939689', '+254721939689', 'verified', true, true, 'Afrimac', 'https://afrimacinternational.com/property/2-bedroom-dsq-apartment-for-sale-parklands-nairobi/'),

('sale', 'broker', '5BR Duplex — Parklands (245 sqm)', 'Elegant 5-bedroom duplex in Parklands. 245 sqm near Westlands and Expressway. From KES 25M.', 'Parklands', 'Parklands, Nairobi', 'apartment', 5, 4, 2637, 25000000, ARRAY['245 sqm', 'DSQ', 'Duplex'], ARRAY['Swimming pool', 'Gym', 'Kids play area', '2 high-speed lifts', 'Ample parking', 'CCTV & intercom', 'Backup generator', 'Borehole'], ARRAY['https://afrimacinternational.com/wp-content/uploads/2026/06/Untitled-design-20.png', 'https://afrimacinternational.com/wp-content/uploads/2026/06/Untitled-design-19.png', 'https://afrimacinternational.com/wp-content/uploads/2026/06/Untitled-design-16.png', 'https://afrimacinternational.com/wp-content/uploads/2026/06/Untitled-design-9.png', 'https://afrimacinternational.com/wp-content/uploads/2026/06/Untitled-design-5.png'], '+254721939689', '+254721939689', 'verified', true, true, 'Afrimac', 'https://afrimacinternational.com/property/elegant-5-bedroom-duplex-for-sale-in-parklands/');
